name: learn_structure_g10
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  http: ^1.1.0
#  http_interceptor: ^1.0.2
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  l: ^4.0.2
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  google_generative_ai: ^0.2.1

  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.8
  lints: ^2.1.0
  test: ^1.24.0
